### PR TITLE
fallocate: add FALLOC_FL_COLLAPSE_SIZE mode

### PR DESCRIPTION
**Pull request by fsareshwala**

### CODE REVIEW

**Comment by fsareshwala** [comment]
Hm, it looks like the machines that Travis CI is running on don't have this option. I'll try and put it in an `#ifdef` or something and update.

**Comment by trbs** [comment]
Thanks !

**Comment by fsareshwala** [comment]
Awesome. Thanks for the merge. Do you have a release cycle that I can wait for or will you push this up immediately?

**Comment by trbs** [comment]
New version with the PR is already out :-)

**Comment by fsareshwala** [comment]
Great! Thank you!

**Pull request merged**
